### ISSUE TITLE
Error with migration

### ISSUE THREAD

**Issue by victorborrasdev** [petervmeijgaard/music-db-api#1]
Hi! I'm following your video course from Mapt, and when doing the first migration with `php artisan migrate --seed` i'm getting the following error while seeding ArtistsTableSeeder:

```
[Symfony\Component\Debug\Exception\FatalErrorException]
  parse error, expecting `';'' or `'{''
```

I don't know anything about php, so I don't even know where to look for to solve this problem :/

**Comment by petervmeijgaard** [comment]
Hi @vborras!
Does the error show which line it occurs?

**Comment by victorborrasdev** [comment]
No, just that text. I paste a screenshot so you can see everything:

![image](https://user-images.githubusercontent.com/8100755/29179028-86009d9a-7df3-11e7-9880-54ad4e425893.png)

**Comment by petervmeijgaard** [comment]
Can you check the PHP version that you're using by typing `php -v`?

**Comment by victorborrasdev** [comment]
Sure, it's 5.6.30

**Comment by petervmeijgaard** [comment]
Alright, can you run `php artisan migrate --seed -vvv`, so with the `-vvv` flag at the end? That'll give you a more detailed explanation of what is going wrong.

Perhaps you can try updating to PHP 7.*. I've tried it on my machine, and it's working as expected.

If you don't want to update to the latest version of PHP, you can SSH into the Homestead Vagrant box and run `php artisan migrate --seed` in there.
This can be accomplished by typing `vagrant ssh`. Now cd into the project directory, which is most likely `home/vagrant/Code/music-db-api` (the path to the project can be found in the `Homestead.yaml`-file). Now, try running the command here and see if it's working.

**Comment by victorborrasdev** [comment]
It works now!! For the record:

- `php artisan migrate --seed -vvv` didn't show any additional info.
- SSHing into vagrant and doing the migration worked.
- Updating to PHP 7.1 worked, I followed the steps in this site: [http://aerendir.me/2015/08/01/how-to-upgrade-php-built-in-your-mac-osx/](http://aerendir.me/2015/08/01/how-to-upgrade-php-built-in-your-mac-osx/)

Thank you so much for your help and your quick response 😃

**Comment by petervmeijgaard** [comment]
Glad I could help! If you run into more problems during the course, feel free to let me know! ☺️

**Comment by petervmeijgaard** [comment]
Also, since you mentioned that you're developing on OS X, I would like to suggest installing [Homebrew](https://brew.sh/index_nl.html). It's a package manager for OS X. This way you can run `brew install php` and update using `brew upgrade`.
